"""Add food_menu to TiffinVendor

Revision ID: a05b7b20cfbb
Revises: 5dadcf2063f9
Create Date: 2025-07-19 18:05:57.887711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a05b7b20cfbb'
down_revision = '5dadcf2063f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tiffin_vendor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('food_menu', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tiffin_vendor', schema=None) as batch_op:
        batch_op.drop_column('food_menu')

    # ### end Alembic commands ###
